# Macro testGPS.mac
/run/initialize

#/vis/open HepRepFile
#/vis/scene/create
#/vis/scene/add/volume
#/vis/sceneHandler/attach
#/vis/viewer/flush

#/vis/scene/add/trajectories
#/vis/scene/add/hits

#/vis/enable

/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/gps/verbose 2

#/vis/scene/endOfEventAction accumulate

#setting up the source
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 65 cm
/gps/pos/halfx 10 cm
/gps/pos/halfy 10 cm

#angles to be released
/gps/ang/type cos
/gps/ang/mintheta 0
/gps/ang/maxtheta 1.57

#energy characteristics
/gps/ene/type Lin
/gps/ene/gradient 1
/gps/ene/intercept 1

#Gamma particles
/gps/particle gamma
/gps/ene/min 10 keV
/gps/ene/max 10 MeV
/run/beamOn 3000000

#/vis/viewer/update


#/vis/enable

#Thermal Neutrons
#/gps/particle neutron
#/gps/ene/min 0.020 eV
#/gps/ene/max 0.030 eV
#/run/beamOn 19840


#Fast Neutrons
/gps/particle neutron
/gps/ene/min 1 MeV
/gps/ene/max 20 MeV
/run/beamOn 29760
#/vis/viewer/update
