# Macro testGPS.mac
/run/initialize

#Setting up HepRepFile output
#Use the flush command to generate a new file

#/vis/open HepRepFile
#/vis/scene/create
#/vis/scene/add/volume
#/vis/sceneHandler/attach
#/vis/viewer/flush

#/vis/scene/add/trajectories
#/vis/scene/add/hits

#/vis/enable

/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/gps/verbose 2

# Enable this command to allow for accumulation of particle onto the visualization file after each "event"
# where each "event" is a beamOn command.
# Otherwise, each beam (instead of each update or flush) will generate a visualization file for HepRep.

#/vis/scene/endOfEventAction accumulate

#setting up the General Particle Source
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 65 cm
/gps/pos/halfx 10 cm
/gps/pos/halfy 10 cm

#angles to be released
/gps/ang/type cos
/gps/ang/mintheta 0
/gps/ang/maxtheta 1.57

# https://www.fe.infn.it/u/paterno/Geant4_tutorial/slides_further/GPS/GPS_manual.pdf
# https://geant4-forum.web.cern.ch/uploads/short-url/lPOPXwh9kot4oJ399P7x49qk01d.pdf

#energy characteristics
/gps/ene/type Lin
/gps/ene/gradient 1
/gps/ene/intercept 1

#Gamma particles
/gps/particle gamma
/gps/ene/min 10 keV
/gps/ene/max 10 MeV
/run/beamOn 3000000

# A summary containing the dosage will be displayed on the text interface after each beamOn command.

# beamOn count should be roughly representative of the payload launch. 

#/vis/viewer/update


#/vis/enable

#Thermal Neutrons
#/gps/particle neutron
#/gps/ene/min 0.020 eV
#/gps/ene/max 0.030 eV
#/run/beamOn 19840


#Fast Neutrons
/gps/particle neutron
/gps/ene/min 1 MeV
/gps/ene/max 20 MeV
/run/beamOn 29760
#/vis/viewer/update
